image: hypriot/rpi-node

cache:
  paths:
  - node_modules/

before_script:
- npm install

deploy:
  script:
  - npm run build
  - ssh-add <(echo "$STAGING_PRIVATE_KEY")
  - ssh -p22 pi@$STAGING_IP "rm -Rf /tmp/hautomation-core-deploy"
  - ssh -p22 pi@$STAGING_IP "mkdir /tmp/hautomation-core-deploy"
  - scp -P22 -r build/* pi@$STAGING_IP:/tmp/hautomation-core-deploy/
  - ssh -p22 pi@$STAGING_IP "cd /tmp/hautomation-core-deploy/install && sh install.sh"
