image: woodyslum/hautomation-ci:8

cache:
  paths:
  - ~/.pkg-cache/

stages:
  - lint
  - test
  - doc
  - build
  - deploy

test:
  stage: test
  script:
  - export NODE_TLS_REJECT_UNAUTHORIZED=0
  - npm --proxy http://192.168.0.2:6286 --https-proxy http://192.168.0.2:6286 --strict-ssl false install
  - npm run --verbose test-ci
  coverage: '/Statements   : \d+\.\d+/'

lint:
  stage: lint
  only:
    - master
  script:
  - set NODE_TLS_REJECT_UNAUTHORIZED=0
  - npm --proxy http://192.168.0.2:6286 --https-proxy http://192.168.0.2:6286 --strict-ssl false install
  - npm run --verbose lint

build:
  stage: build
  script:
  - set NODE_TLS_REJECT_UNAUTHORIZED=0
  - npm --proxy http://192.168.0.2:6286 --https-proxy http://192.168.0.2:6286 --strict-ssl false install
  - npm run --verbose build
  artifacts:
    paths:
    - build/*

deploy:
  stage: deploy
  only:
    - master
  script:
  - ssh-add <(echo "$STAGING_PRIVATE_KEY")
  - ssh -p22 $STAGING_USER@$STAGING_IP "rm -Rf $STAGING_TMP_FOLDER/hautomation-core-deploy"
  - ssh -p22 $STAGING_USER@$STAGING_IP "mkdir $STAGING_TMP_FOLDER/hautomation-core-deploy"
  - scp -P22 -r build/* pi@$STAGING_IP:$STAGING_TMP_FOLDER/hautomation-core-deploy/
  - ssh -p22 $STAGING_USER@$STAGING_IP "cd $STAGING_TMP_FOLDER/hautomation-core-deploy/scripts && sh install.sh $STAGING_USER $STAGING_GROUP $STAGING_INSTALLATION_FOLDER"
  environment:
    name: staging
    url: $STAGING_URL
