image: woodyslum/hautomation-ci:12.14-1

stages:
  - build
  - lint
  - test
  - doc
  - deploy

cache:
  paths:
    - node_modules/

test:
  stage: test
  except:
  - tags
  script:
  - export NODE_TLS_REJECT_UNAUTHORIZED=0
  - npm config set strict-ssl false
  - npm run --verbose cov
  coverage: '/Statements   : \d+\.\d+/'

lint:
  stage: lint
  only:
    - master
  except:
  - tags
  script:
  - export NODE_TLS_REJECT_UNAUTHORIZED=0
  - npm config set strict-ssl false
  - npm run --verbose lint

build:
  stage: build
  script:
  - export NODE_TLS_REJECT_UNAUTHORIZED=0
  - npm config set strict-ssl false
  - rm -Rf package-lock.json
  - npm install
  - npm rebuild
  - echo "{\"commit\":\"$(echo $CI_COMMIT_SHA | head -c8)\"}" > version.json
  - npm run --verbose build
  - npm run --verbose build-deb
  artifacts:
    paths:
    - build/*
