image: hypriot/rpi-node

cache:
  paths:
  - node_modules/

before_script:
- npm install

test:
  script:
  - npm run test-ci
  coverage: '/Statements   : \d+\.\d+/'

lint:
  script:
  - npm run lint

doc:
  script:
  - npm run doc
  - npm run doc-apis

deploy:
  script:
  - npm run build

artifacts:
  paths:
  - build/*
